# Generated by Django 2.0.3 on 2018-05-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180225_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=10000)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='register',
            name='emailid',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=700),
        ),
    ]
